### ISSUE TITLE
Could you add more examples and/or explanation of your plugins possibilities?

### ISSUE THREAD

**Issue by janpeeters70** [mgmeyers/obsidian-contextual-typography#6]
Hi, I'm trying to better understand your plugin. It feels powerful, thanks for developing it. I was wondering if you could add some more examples and/or explanation of (possibilities of the) syntax on your Github page. Or maybe point to a page where the syntax possibilities are explained? Thanks in advance.

**Comment by SimonEast** [comment]
Yes, good question. I'm pretty new to Obsidian and like the idea of this plugin, but how do you insert custom CSS into your file?

**Comment by zhl111** [comment]
Yes, I have absolutely no idea how this plugin is supposed to work.

**Comment by ryran** [comment]
A few years later and here I am with the same question. I suspect it could make possible some of the things I want to do, but I have no idea where to start.

**Comment by j-peeters** [comment]
I would also still be very interested to know more.

**Comment by Kirxii** [comment]
Alright, after I've read through the html code of obsidian notes before and after the plugin has turned on, here's what I've found. So it adds the html property called `data-tag-name` to every `<div>` element that's a direct child of `.markdown-rendered`, aka Preview mode. the value of `data-tag-name` is what type of html element it is.

For example, a Heading 1 `h1` would have the value as `"h1"`, a paragraph `<p>` would have the value of `"p"` and so on. But why would you want that? Well, to make contextual typography (as in the name of the plugin), which just means that changes how each elements react when next to each other.

For example, if you have a heading 1 `h1` and below it is a heading 2 `h2`, if you have the line height for each of them separately, when combined, there will be a big gap between heading 1 and 2. In which you most likely don't want that, and unable to change the line height of each of them since that would also affect each header's line height when standing on its own. And since Reading mode puts every element inside a `<div>`, you can't have a selector to select a heading 1 that is a direct sibling to a heading 2 underneath it. With contextual typography however, the divs now have a property for you to select a `<h2>` element that is directly after a `<h1>` element, like this

```css
.markdown-rendered div[data-tag-name="h1"] + div > h2 {
    margin-top: -1.5rem;
}
```

**Comment by alikuba** [comment]
It helped me with indented headers
```
.markdown-preview-view div[data-tag-name="h1"] + div > p,
.markdown-preview-view div[data-tag-name="h2"] {
	padding-left: 1.2em;
}

.markdown-preview-view div[data-tag-name="h2"] + div > p,
.markdown-preview-view div[data-tag-name="h3"] {
	padding-left: 2.4em;
}

.markdown-preview-view div[data-tag-name="h3"] + div > p,
.markdown-preview-view div[data-tag-name="h4"] {
	padding-left: 3.6em;
}

.markdown-preview-view div[data-tag-name="h4"] + div > p,
.markdown-preview-view div[data-tag-name="h5"] {
	padding-left: 4.8em;
}

.markdown-preview-view div[data-tag-name="h5"] + div > p,
.markdown-preview-view div[data-tag-name="h6"] {
	padding-left: 6em;
}
```

<img width="633" height="824" alt="Image" src="https://github.com/user-attachments/assets/e3ca3bfc-406c-44ee-b90f-966cb56cc1b8" />

**Comment by Kirxii** [comment]
@alikuba wouldn't it going to mess up the indentation if the heading is completely off the screen, to the point of it not being in the DOM?

**Comment by alikuba** [comment]
I think, it can't do that. 

Btw, this plugin is not so useful in my opinion.

Let's assume:
hN - h1, h2, h3, h4, h5 or h6

Argument:
any `div[data-tag-name="hN"]` can be replaced with `el-hN`

Conclusion:
Plugin adds feature that is already there

I upgraded my previous code and turned it into cssclass

```css
.indented-headers .el-h1 + .el-p,
.indented-headers .el-h2 {
	padding-left: 1.2em;
}

.indented-headers .el-h2 + .el-p,
.indented-headers .el-h3 {
	padding-left: 2.4em;
}

.indented-headers .el-h3 + .el-p,
.indented-headers .el-h4 {
	padding-left: 3.6em;
}

.indented-headers .el-h4 + .el-p,
.indented-headers .el-h5 {
	padding-left: 4.8em;
}

.indented-headers .el-h5 + .el-p,
.indented-headers .el-h6 {
	padding-left: 6em;
}
```

<img width="650" height="630" alt="Image" src="https://github.com/user-attachments/assets/95f8a2a8-8866-4837-bc89-225a5b4bb725" />
